apiVersion: apps/v1
kind: Deployment
metadata:
  name: subs
  namespace: securelink
  labels:
    app: subs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subs
  template:
    metadata:
      labels:
        app: subs
    spec:
      serviceAccountName: subs-sa
      containers:
      - name: api
        image: ghcr.io/your-org/subs:0.1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_DSN
          valueFrom:
            secretKeyRef:
              name: subs-secrets
              key: DB_DSN
        - name: SUBS_INTERNAL_TOKEN
          valueFrom:
            secretKeyRef:
              name: subs-secrets
              key: SUBS_INTERNAL_TOKEN
        - name: WATCH_NAMESPACE
          value: "securelink"
        - name: WATCH_LABEL_SELECTOR
          value: "app=xray,component=clients"
        - name: POOL_LABEL_KEY
          value: "pool"
        - name: CM_CLIENTS_KEY
          value: "clients.json"
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: subs
  namespace: securelink
spec:
  selector:
    app: subs
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  type: ClusterIP
