name: Build subs image

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'subs-mvp/**'
      - 'subs-mvp-2025-08-21.zip'
      - '.github/workflows/build-subs.yml'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare source dir
        run: |
          if [ -d subs-mvp ]; then
            echo "subs-mvp dir exists"
          else
            unzip -o subs-mvp-2025-08-21.zip -d .
            [ -d subs-mvp ] || { echo "subs-mvp dir not found"; exit 1; }
          fi

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./subs-mvp
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/subs:latest
            ghcr.io/${{ github.repository_owner }}/subs:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/subs:${{ github.run_id }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
